FROM httpd:2.4.53

MAINTAINER nhattien.lam.545@gmail.com

COPY conf/httpd.conf /usr/local/apache2/conf/httpd.conf
COPY conf/httpd-vhosts.conf /usr/local/apache2/conf/extra/httpd-vhosts.conf
COPY package /usr/local/apache2/htdocs